tidev/node-titanium-sdk

lib/jsanalyze.js, package.json, yarn.lock
https://jira.appcelerator.org/browse/TIMOB-24609
Related to: 
- appcelerator/titanium_mobile#8972
- appcelerator/titanium_mobile#8974
Once appcelerator/titanium_mobile#8974 is merged and this PR is merged, then appcelerator/titanium_mobile#8972 needs to be re-done to simply upgrade node-titanium-sdk 0.1.0 to 0.2.0
This bumps the version to 0.2.0, and replaces uglify-js usage with babel libraries. This is a port of the original PR for appcelerator/titanium_mobile#8972
=> [TIMOB-24609] ES 6 Support

README.md, lib/jsanalyze.js, package.json
- Need to resolve path to babel preset using require, otherwise it looks for rest to be installed in the user's project.
- Use babel.transform to minify since once we traverse an AST we can re-use it. Long-term fix would be to make our code that does Ti.* symbol searches a babel plugin so we can do one pass with it and presets.
=> Fix [TIMOB-24662] CLI: Build errors out with "Couldn't find preset "babili" relative to directory" when deploy type is test

lib/android.js
- Fix `\r\n` line-ending detection on Windows
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24689)
=> [TIMOB-24689] Android: Fix line-ending detection for Windows

lib/titanium.js, package.json
- Only configure the platform we intent to build, for faster build times
- Should not configure `windows` or `ios`
```
appc run -p android --build-only
```
=> [TIMOB-24750] Only configure target platform

lib/adb.js, package.json
- Induce a 100ms delay before sending the initial `ADB.exec()` command
- Close all running emulators
- Repeat `run` command a number of times
```
appc run -p android -T emulator
```
- Should not see error below, project should run on emulator
```
[ERROR] Failed to install apk on "emulator-5554"
[ERROR] Error: device not found
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24906)
=> [TIMOB-24906] Android: Delay sending initial adb command

lib/android.js
JIRA: https://jira.appcelerator.org/browse/TIMOB-24787
- Filter the files based off an ignoreFiles list
- I think we should do the following also
- Update the node-appc check to prevent this bug occuring in other places in the future, i.e. validate the range passed in there too, rather than expecting it to be done in every place we use node-appc.version.whatever
1. Install a version of Android build-tools that is lower than the minimum required version (or edit the minimum in the SDK to be higher than whatever you have)
2. Build a project for Android
- Should not error out with the error in ticket description, should throw an error about `Missing required Android SDK tools:`
=> [TIMOB-24787] Fixed issue when .DS_Store exists in build-tools dir

lib/titanium.js, package.json
Best used to filter platform-specific subdirectories of Resources in apps. This is preferred over availablePlatformNames which just gives you the list of available platforms for the given SDK version and OS (so for example we'll end up copying windows subdirectories on a mac build of a cross-platform app). We "fixed" this in the iOS build to use a regexp, but never fixed it in Android. I decided it'd be best to migrate the array to node-titanium-sdk as an export.
=> Add an export to provide the full array of all platform names we've supported.

lib/adb.js, lib/emulators/avd.js, package.json
- Increase `100ms` delay to `200ms` before sending command
- Implement `waitForResponse` for `trackDevices` as the initial response may not contain any response data
- `ps` now requires the `-A` parameter to list all process results. Implement backwards-compatible `adb.ps` method
- Fix `getPid` to use new `adb.ps` method
- Remove `-no-boot-anim` as this flag prevents the Android O emulator from booting
- Increase `-partition-size` to `512`
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24900)
=> [TIMOB-24900] Support Android O changes

lib/adb.js, package.json
- When parsing `adb devices`, always wait for response data instead of just a response
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24906)
=> [TIMOB-24906] Android: Wait for response when parsing devices

lib/adb.js
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25742
**Summary:**
- Was failing to install because our `adb install` command was passing argument `-d`, which is only supported on Android 4.2 and higher.
- Now checks the device's API Level and only adds the `-d` argument if supported on device.
- Note that install was failing near the end of the install, once the APK had been finished copying over to the device. So, it's better to check device API Level in advance for best performance.
**Test:**
Run the test attached to [TIMOB-25742](https://jira.appcelerator.org/browse/TIMOB-25742).
=> [TIMOB-25742] Fixed adb issue where it fails to install to Android 4.1 devices

lib/android.js
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-25865
**Summary:**
- This avoids an unnecessary "too new" warning from being logged after every build. Will now use the preferred build-tools version instead of always selecting newest version.
- Modified to log which version(s) are supported _(in parenthesis)_ if installed build-tools, platform-tools, and SDK is older than supported. This way the end-user has a clue on what to install.
**Note:**
Our `appc.version.satisfies()` function returns boolean values `true` and `false`... as well as the string `'maybe'` if above supported version range (ie: too new). Doing an if-check on the `'maybe'` string was what was biting us here.
---
**Test:**
1. Open the Android SDK Manager.
2. Install "build-tools" versions 27.x and 26.x, if not done …
=> [TIMOB-25865] Android: Modified CLI to not select "build-tools" version newer than supported if a supported version is installed

lib/adb.js
**JIRA:**
- https://jira.appcelerator.org/browse/TIMOB-26099
- https://jira.appcelerator.org/browse/TIMOB-25867
**Summary:**
- Modified `appc run` to use same intent settings the Android OS uses when tapping on an app.
* We were missing intent action "MAIN and category "LAUNCHER".
- Fixes issue where pressing "Home" button after `appc run` app launch and then tapping on the app onscreen would not resume the app. Would launch a new splash-screen, but not run the app.
- Fixed regression caused by [TIMOB-25867](https://jira.appcelerator.org/browse/TIMOB-25867) where "Restart Required" dialog would be displayed infinitely on app launch on Pixel XL.
**Test:**
Run the below test on a Pixel XL, Android 4.1 device, and in the Android emulator.
1. Build and run the below code via Appcelerator …
=> [TIMOB-26099] Android: Modified "appc run" to launch app with same intent as Android OS when tapping app

lib/android.js
- Update `emulator` tooling path, include fallback to old path
- Build and run a project using an x86 emulator
- `appc run -p android`
- Emulator runs correctly
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26126)
=> [TIMOB-26126] Android: Update emulator path

lib/android.js, package-lock.json, package.json
https://jira.appcelerator.org/browse/TIMOB-26173
=> [TIMOB-26173] Add default Android Studio SDK install paths to lookup

lib/jsanalyze.js, package-lock.json, package.json
- Generate source maps during development builds or through opt-in `tiapp.xml` property `<source-maps>true</source-maps>`
```JS
class Window {
constructor () {
this.view = Ti.UI.createWindow({ backgroundColor: 'gray' });
this.button = Ti.UI.createButton({ title: 'CLICK' });
this.view.add(this.button);
}
show () {
this.view.open();
}
}
new Window().show();
```
- Build an Android Titanium app with `transpile` enabled, debug using Chrome
- `appc run -p android --debug-host /127.0.0.1:51388`
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26333)
=> [TIMOB-26333] Generate source maps

lib/jsanalyze.js, package-lock.json, package.json
- Although rare, `copySync` can fail to copy the dependency correctly
- Validate `package.json` exists as a quick check to make sure the files have been copied. Otherwise it would only check for the existence of an empty folder and not attempt to copy the dependency again.
- Retry if the copy fails
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26621)
=> [TIMOB-26621] Retry upon dependency copy failure

lib/android.js
In setting up my new work laptop, I'm trying to streamline the process to get set up - including just installing what I need via home-brew whenever possible.
I'm working on a bash setup script for our usage internally and possibly also as an eventual "installer" for users: https://github.com/sgtcoolguy/macos-setup
Anyways, homebrew cask can install Android SDK/NDK, but it puts them in a location e don't automatically detect: `/usr/local/share/android-sdk` and `/usr/local/share/android-ndk`
=> fix: detect installs of android sdk/ndk where brew cask puts them

lib/jsanalyze.js, tests/jsanalyze_test.js
Relates to https://jira.appcelerator.org/browse/TIMOB-26742
This excludes web specific polyfills from being injected into user apps on transpilation. I noticed that web.dom.iterable was injected pretty frequently and is entirely irrelevant to Titanium apps.
=> fix: do not include web polyfills

lib/jsanalyze.js
This is a simple fix: if parsing a JS file fails, fall back to trying to parse as a script explicitly and allowing returns outside functions.
The came up from trying to use the official mocha package in our test suite. The build of the app fails because `mkdirp` has a `bin\cmd.js` file using a return "globally" which is allowed under Node.
I think there's a larger discussion to be had as to whether we should be parsing/transpiling/minifying 3rd party node_modules, but for now I think having a fall back like this makes some sense.
=> fix: fall back to looser parsing if necessary

lib/babel-plugins/ti-api.js, lib/jsanalyze.js, package-lock.json, package.json, tests/jsanalyze_test.js
This avoids the need to explicilty require @babel/types and @babel/traverse as direct dependencies; as well as avoids needing to traverse the AST twice. This should allow for a faster CLI build of apps.
Before we'd parse the JS file, then traverse the AST once just to scan for Ti API usage- then moving on to setting up babel presets/plugins for transpile/minify/etc and parsing the code and traversing the AST *again*! So this is a fairly "simple" change that should speed up the build by a noticeable amount (hopefully).
=>  refactor: gather Ti API usage inline with rest of babel plugins

lib/jsanalyze.js, package-lock.json, package.json, tests/jsanalyze_test.js
Relates to appcelerator/titanium_mobile#10567
We may need to move polyfilling up to the SDK build process itself to support doing things like async functions in our bootstrap code. (Specifically when I'm trying to add support for things like Node's `assert.rejects()`)
If we do so, polyfilling during the user app build based on usage is no longer necessary.
This PR is meant to remove polyfilling from node-titanium-sdk altogether and would be merged/coordinated with the PR in the SDK that did the polyfilling during SDK build itself instead.
=> Polyfill removal

lib/jsanalyze.js, package-lock.json, package.json, tests/jsanalyze_test.js
This is causing master builds to fail suddenly on the SDK. It appears to be from a. fluke in how the node_modules folders are getting constructed that this particular plugin lives underneath preset-env and resolution from our jsanalyze.js file fails. In a local test, it appears we don't need to manually add this plugin to the list and it just gets run when the targeted platform needs it (via preset-env).
=> Remove async transform explicit plugin listing

lib/jsanalyze.js, package-lock.json, package.json, tests/jsanalyze_test.js, tests/resources/input.nonexistent.sourcemapfile.js, tests/resources/input.nonexistent.sourcemapfile.js.map
**JIRA**: https://jira.appcelerator.org/browse/TIMOB-27465
=> fix(jsanalyze): handle when sourcemappingURL points to non-existent file

lib/jsanalyze.js, package-lock.json, package.json, tests/jsanalyze_test.js
**JIRA**: https://jira.appcelerator.org/browse/TIMOB-27167
**Description**
Integrates [appcelerator/babel-plugin-transform-titanium](https://github.com/appcelerator/babel-plugin-transform-titanium) 0.1.1
Will require changes to [appcelerator/titanium_mobile](https://github.com/appcelerator/titanium_mobile) to pass along the options used by the plugin.
The goal here is pass along an object with static values about the target platform/app that our custom babel plugin can use to inline the static values and replace typical platform sniffing expressions. (As well as do some of what appcelerator/alloy has done in it's compile for years, like having special `OS_*`, `DIST_*`, `ENV_*` defines). See the plugin's [README](https://github.com/appcelerator/babel-plugin-transform-titanium/blob/master/RE …
=> feat(jsanalyze): integrate babel-plugin-transform-titanium

lib/emulators/avd.js, package-lock.json, package.json
- Emulator fails to launch as it's unable to find a valid port
- Error code property `error.errno` should only return numeric values, `error.code` should be used instead
- Attempt to build Titanium application for emulator
- Emulator should launch successfully and application will build
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-27723)
=> fix(android): emulator fails to launch

lib/adb.js, lib/emulators/avd.js, package-lock.json, package.json
**JIRA**: https://jira.appcelerator.org/browse/TIMOB-27750
Tested this with the same emulator that exhibited the issue before and it worked with these changes.
I also wiped the snapshot for the emulator so it had to do a full boot and that also worked.
=> fix(avd): consider listed emulator as running even if state !== 'device'

lib/android.js, package-lock.json, package.json
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27755
**Cherry-pick of PR:** #143
=> feat(android)(4_4_X): update android ndk folder detection

lib/jsanalyze.js, package-lock.json, package.json
The [source-map-support](https://github.com/evanw/node-source-map-support#readme) package falsely identifies the `//# sourceMappingUrl=` line that we add to the transpiled code as the actual source mapping for the `jsanalyze.js` file. This leads to a nasty crash that hides the original error when `source-map-support` is enabled and it tries to read a non-existent source map while preparing the original error stack trace.
```sh
SyntaxError: Unexpected token m in JSON at position 0
at JSON.parse (<anonymous>)
at Object.parseSourceMapInput (../../node_modules/source-map/lib/util.js:433:15)
at new SourceMapConsumer (../../node_modules/source-map/lib/source-map-consumer.js:17:22)
at mapSourcePosition (../../node_modules/source-map-support/source-map-support.js:200:14)
at wrapCallSite …
```
=> fix: obfuscate source map line construction

lib/adb.js, package-lock.json, package.json
errno was removed in Node.js 13/14
Fixes [TIMOB-28464](https://jira.appcelerator.org/browse/TIMOB-28464)
=> fix(adb): check err.code instead of err.errno on socket error

lib/adb.js, lib/android.js
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-28496
**Note:**
The Android SDK's tools and emulator are 64-bit now. We no longer need to check for 32-bit libraries like this anymore.
**Test:**
Build and run a Titanium app project on 64-bit Linux to the Android emulator.
=> fix(android): build on 64bit Linux fails if no 32bit libs available

lib/android.js, package-lock.json, package.json, tests/adb_test.js, tests/avd_test.js
JIRA: https://jira.appcelerator.org/browse/TIMOB-28519
Removes the requirement for the dx tool (removed in the API 31 install) and the also removes the tools no longer directly referenced in the SDK build scripts.
This will need a follow up on the Titanium CLI repo to no longer as that checks that they exist in the `ti setup check` command, no breakage seen in Studio
=> No longer require tooling that has been removed and/or is no longer referenced by the SDK build

lib/titanium.js
Make it possible to use `-l debug` instead of `--log-level debug`
=> feat(all): add -l for --log-level

lib/adb.js
merge https://github.com/tidev/node-titanium-sdk/pull/629 for less lint warnings first
This will set the default to IPv4 for node 17,18,19 support. Beginning with 17 the default setting of `0` will select a IPv6 (https://stackoverflow.com/a/73732144/5193915) and it won't connect to ADB to get the device or emulator and stops.
Setting it to IPv4 will build apps with all node versions up to 19 again!
We could make this a config setting later but since the default was ipv4 before too it shouldn't hurt to keep it at that level.
=> chore: default to ipv4

.eslintrc, lib/android.js, lib/builder.js, lib/emulators/avd.js, lib/emulators/genymotion.js, lib/titanium.js, package-lock.json
should merge https://github.com/tidev/node-titanium-sdk/pull/598 first
* remove some eslint warnings
* remove ANDROID_NDK_NOT_FOUND warning (NDK is installed by the CLI since https://github.com/tidev/titanium_mobile/pull/12711)
* add openjdk link to the "install jdk" message and fixed oracle jdk link
* changing avd.js to include partiton-size and image only if it is set (fixes M1 Android black emulator issues)
=> chore(all): remove ndk message, fix eslint warnings

lib/tiappxml.js
allows you to use `platform="android"` for `<id>`
Tested on Linux/Andorid with:
```xml
<id platform="android">com.miga.test_android</id>
<id>com.miga.test</id>
```
and
```xml
<id>com.miga.test</id>
<id platform="android">com.miga.test_android</id>
```
both time it will use `com.miga.test_android` at the end.
**TODO**
Need to check it on iOS
=> chore: use platform for id

lib/emulators/avd.js
I can't test it as I don't have a Arm Mac.
Having those parameters on an Arm Mac won't start the emulator, it will stop with a black screen.
In the old PR at https://github.com/tidev/node-titanium-sdk/pull/629 I've already added a check so it won't include it. But if you have a SDCard assigned in your emulator it will still use the `-sdcard` parameter. 
This PR will ignore both parameters if you are using an Arm Mac. The CPU check part is from:
https://github.com/nodejs/node/issues/41900#issuecomment-1113511254
=> fix: arm mac emulator fix

.github/workflows/build.yml, .github/workflows/publish.yml, lib/jsanalyze.js, tests/adb_test.js, tests/avd_test.js
Currently if you have npm modules that have source map files compiling will fail with:
```
[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
at Object.resolve (node:path:1101:7)
at Object.analyzeJs (/home/miga/.titanium/mobilesdk/linux/12.5.0/node_modules/node-titanium-sdk/lib/jsanalyze.js:201:26)
at ProcessJsTask.transformAndCopy (/home/miga/.titanium/mobilesdk/linux/12.5.0/cli/lib/tasks/process-js-task.js:308:31)
at AndroidBuilder.<anonymous> (/home/miga/.titanium/mobilesdk/linux/12.5.0/cli/lib/tasks/process-js-task.js:218:17)
at data.result (file:///usr/local/lib/node_modules/titanium/src/cli.js:322:15)
at new Promise (<anonymous>)
at file:///usr/local/lib/node_modules/titanium/src/cli.js:320:26
```
The fix is to exclude files …
=> fix: node_modules sourceMaps
